spring:
  profiles: dev

  datasource:
    initialization-mode: always    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.78.102.56:3000/SpringDev?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Ali9411&&
        
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: MYSQL
    show-sql: true